Fix return value of DataDeskRequireTagParameter(s). Fix array declara…
ryanfleury/data_desk pull request #26
Opened 2020-12-12 06:12 UTC by thePHTest

…tion causing graph output to spit out a bunch of extra newlines.

2020-12-12 07:29 UTC, thePHTest commented
My apologies for not syncing to master first. I'll make sure to do so next time. Fortunately it looks like it can auto-merge just fine :)

2021-01-15 16:02 UTC, ryanfleury requested changes
This isn't quite correct; `DataDeskRequireTagParameter` should allow 0 for a `result` parameter.

2021-01-15 17:10 UTC, thePHTest commented on source/data_desk.h
> +        if(tag_param)
So are you thinking:
`if(tag_param)
{
  if(result)
  {
    *result = tag_param;
  }
  found = 1;
}`

And this way you can query for the required parameter without having a result allocated.

2021-01-20 18:17 UTC, ryanfleury commented on source/data_desk.h
> +        if(tag_param)
Yep, that's the idea. So you don't need to pass in a pointer if you are just querying the existence of something (which would just be annoying boilerplate).

2021-01-20 18:17 UTC, merged